// Generated by CoffeeScript 1.6.2
(function() {
  var Question;

  module.exports = Question = (function() {
    function Question() {}

    Question.prototype.ask = function(question, format, fn) {
      var stdin, stdout,
        _this = this;

      stdin = process.stdin;
      stdout = process.stdout;
      stdout.write("" + question + " ");
      return stdin.once('data', function(data) {
        var msg, rule;

        data = data.toString().trim();
        if (format.test(data)) {
          return fn(data.trim());
        } else {
          msg = "" + 'Invalid entry, it should match:'.red;
          rule = "" + (format.toString().cyan);
          stdout.write("\t" + msg + " " + rule + "\n");
          return _this.ask(question, format, fn);
        }
      }).resume();
    };

    return Question;

  })();

}).call(this);

/*
//@ sourceMappingURL=question.map
*/
