// Generated by CoffeeScript 1.6.2
(function() {
  var ArrayUtil, ObjectUtil;

  ObjectUtil = require('../utils/object_util');

  module.exports = ArrayUtil = (function() {
    function ArrayUtil() {}

    ArrayUtil.find = function(src, search) {
      var i, v, _i, _len;

      for (i = _i = 0, _len = src.length; _i < _len; i = ++_i) {
        v = src[i];
        if (!(search instanceof Object)) {
          if (v === search) {
            return {
              item: v,
              index: i
            };
          }
        } else {
          if (ObjectUtil.find(v, search) != null) {
            return {
              item: v,
              index: i
            };
          }
        }
      }
      return null;
    };

    ArrayUtil["delete"] = function(src, search) {
      var item;

      item = ArrayUtil.find(src, search);
      if (item != null) {
        return src.splice(item.index, 1);
      }
    };

    ArrayUtil.has = function(source, search) {
      return (ArrayUtil.find(source, search)) != null;
    };

    ArrayUtil.replace_into = function(src, index, items) {
      items = [].concat(items);
      src.splice(index, 1);
      while (items.length) {
        src.splice(index++, 0, items.shift());
      }
      return src;
    };

    return ArrayUtil;

  })();

}).call(this);

/*
//@ sourceMappingURL=array-util.map
*/
