// Generated by CoffeeScript 1.6.3
(function() {
  var FnUtil,
    __slice = [].slice;

  module.exports = FnUtil = (function() {
    function FnUtil() {}

    FnUtil.proxy = function() {
      var fn, params;
      fn = arguments[0], params = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      return function() {
        var inner_params;
        inner_params = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return fn.apply(null, params.concat(inner_params));
      };
    };

    return FnUtil;

  })();

}).call(this);

/*
//@ sourceMappingURL=fn-util.map
*/
