// Generated by CoffeeScript 1.6.2
(function() {
  var MinifyUtil, uglify;

  uglify = require('uglify-js');

  module.exports = MinifyUtil = (function() {
    function MinifyUtil() {}

    MinifyUtil.min = function(contents) {
      var ast, compiled, stream;

      ast = uglify.parse(contents);
      stream = uglify.OutputStream();
      ast.print(stream);
      return compiled = stream.toString();
    };

    return MinifyUtil;

  })();

}).call(this);

/*
//@ sourceMappingURL=minify-util.map
*/
