// Generated by CoffeeScript 1.6.2
(function() {
  var StringUtil;

  module.exports = StringUtil = (function() {
    function StringUtil() {}

    StringUtil.titleize = function(str) {
      var index, word, words, _i, _len;

      words = str.match(/[a-z]+/gi);
      for (index = _i = 0, _len = words.length; _i < _len; index = ++_i) {
        word = words[index];
        words[index] = StringUtil.ucasef(word);
      }
      return words.join(" ");
    };

    StringUtil.ucasef = function(str) {
      var output;

      output = str.substr(0, 1).toUpperCase();
      return output += str.substr(1).toLowerCase();
    };

    return StringUtil;

  })();

}).call(this);

/*
//@ sourceMappingURL=string-util.map
*/
