// Generated by CoffeeScript 1.6.3
var $argv, colors, examples, optimist, optimistic, usage, version;

optimist = require('optimist');

colors = require('colors');

version = require('./utils/version');

usage = "Polvo " + ('v' + version).grey + "\n" + 'Polyvalent cephalopod mollusc'.grey + "\n\n" + 'Usage:' + "\n  polvo [" + 'options'.green + "] [" + 'params'.green + "]";

examples = "Examples:\n  polvo -c\n  polvo -cs\n  polvo -w\n  polvo -ws\n  polvo -wsf custom-config-file.yml";

$argv = process.argv;

optimistic = null;

exports.help = function() {
  return "" + (optimistic.help()) + "\n" + examples;
};

exports.argv = function(opts) {
  var injection, key, options, val;
  if (opts != null) {
    options = opts;
  }
  if (typeof global_options !== "undefined" && global_options !== null) {
    if (options == null) {
      options = global_options;
    }
  }
  if (options == null) {
    options = {};
  }
  injection = [];
  for (key in options) {
    val = options[key];
    injection.push(key.length === 1 ? "-" + key : "--" + key);
    injection.push("" + val);
  }
  process.argv = $argv.slice(0).concat(injection);
  optimistic = optimist(process.argv).usage(usage).alias('w', 'watch').boolean('w').describe('w', "Start watching/compiling in dev mode").alias('c', 'compile').boolean('c').describe('c', "Compile project in development mode").alias('r', 'release').boolean('r').describe('r', "Compile project in release mode").alias('s', 'server').boolean('s').describe('s', "Serves project statically, options in config file").alias('f', 'config-file').string('f').describe('f', "Path to a different config file").describe('stdio', 'Pipe stdio when forking `polvo` as a child process').boolean('stdio').describe('base', 'Path to app\'s root folder (when its not the current)').string('base').alias('v', 'version').boolean('v').describe('v', 'Show Polvo\'s version').alias('h', 'help').boolean('h').describe('h', 'Shows this help screen');
  return optimistic.argv;
};

exports.argv();

/*
//@ sourceMappingURL=cli.map
*/
