// Generated by CoffeeScript 1.6.3
(require('source-map-support')).install({
  handleUncaughtExceptions: false
});

module.exports = function(options, io) {
  var Cli, argv, cli, compiler, config, debug, error, info, log, server, version, warn, _ref;
  if (options == null) {
    options = {};
  }
  global.cli_options = options;
  global.__stdout = (io != null ? io.out : void 0) || null;
  global.__stderr = (io != null ? io.err : void 0) || null;
  Cli = require('./cli');
  version = require('./utils/version');
  log = require('./utils/log')('polvo');
  argv = (cli = new Cli).argv;
  _ref = log, error = _ref.error, warn = _ref.warn, info = _ref.info, debug = _ref.debug, log = _ref.log;
  if (argv.version) {
    return log(version);
  } else if (argv.compile || argv.watch || argv.release) {
    config = require('./utils/config');
    if (config != null) {
      compiler = require('./core/compiler');
      if (argv.server && (config != null)) {
        server = require('./core/server');
      }
      if (argv.compile || argv.watch) {
        compiler.build();
        if (argv.server) {
          return server();
        }
      } else if (argv.release) {
        console.log('merda');
        compiler.release();
        if (argv.server) {
          return server();
        }
      }
    }
  } else {
    return log(cli.help());
  }
};

/*
//@ sourceMappingURL=polvo.map
*/
