// Generated by CoffeeScript 1.6.3
(function() {
  (require('source-map-support')).install({
    handleUncaughtExceptions: false
  });

  module.exports = function(options, io) {
    var Cli, argv, cli, compiler, config, debug, error, info, log, server, version, warn, _ref;
    if (options == null) {
      options = {};
    }
    global.cli_options = options;
    global.__stdout = (io != null ? io.out : void 0) || null;
    global.__stderr = (io != null ? io.err : void 0) || null;
    version = require('./utils/version');
    config = require('./utils/config');
    log = require('./utils/log')('polvo');
    Cli = require('./cli');
    _ref = log, error = _ref.error, warn = _ref.warn, info = _ref.info, debug = _ref.debug, log = _ref.log;
    argv = (cli = new Cli).argv;
    if (argv.version) {
      return log(version);
    } else if (argv.compile || argv.watch || argv.release) {
      if (config != null) {
        compiler = require('./core/compiler');
        if (argv.server && (config != null)) {
          server = require('./core/server');
        }
        if (argv.compile || argv.watch) {
          compiler.build();
          if (argv.server) {
            return server();
          }
        } else if (argv.release) {
          console.log('merda');
          compiler.release();
          if (argv.server) {
            return server();
          }
        }
      }
    } else {
      return log(cli.help());
    }
  };

}).call(this);

/*
//@ sourceMappingURL=polvo.map
*/
