// Generated by CoffeeScript 1.6.3
var closest_node_modules, config, debug, dirs, error, exts, fs, info, log, path, plugin, plugins, resolve, resolve_file, resolve_id, resolve_index, resolve_module, warn, _i, _len, _ref;

path = require('path');

fs = require('fs');

config = require('../utils/config');

dirs = require('../utils/dirs');

plugins = require('../utils/plugins');

log = require('../utils/log')('scanner/resolve');

_ref = log, error = _ref.error, warn = _ref.warn, info = _ref.info, debug = _ref.debug, log = _ref.log;

exts = [];

for (_i = 0, _len = plugins.length; _i < _len; _i++) {
  plugin = plugins[_i];
  if (plugin.output === 'js') {
    exts = exts.concat(plugin.exts);
  }
}

resolve = module.exports = function(filepath, id) {
  var caller, dirpath, file;
  id = id.replace(/\.js$/m, '');
  file = resolve_id(filepath, id);
  dirpath = path.dirname(filepath);
  if (file != null) {
    return path.resolve(file);
  }
  caller = path.relative(dirs.pwd, filepath);
  error("Module '" + id + "' not found for '" + caller + "'");
  return null;
};

resolve_id = function(filepath, id) {
  var file, idpath, seg, segs;
  if (id[0] !== '.') {
    return resolve_module(filepath, id);
  }
  segs = [].concat(id.split('/'));
  idpath = path.dirname(filepath);
  while (segs.length) {
    seg = segs.shift();
    idpath = path.resolve(idpath, seg);
  }
  if ((file = resolve_file(idpath))) {
    return file;
  }
  if ((file = resolve_module(filepath, id))) {
    return file;
  }
  if ((file = resolve_index(idpath))) {
    return file;
  }
};

resolve_file = function(filepath) {
  var ext, tmp, _j, _len1;
  for (_j = 0, _len1 = exts.length; _j < _len1; _j++) {
    ext = exts[_j];
    tmp = filepath;
    tmp = tmp.replace(ext, '');
    tmp += ext;
    if (fs.existsSync(tmp)) {
      return tmp;
    }
  }
  return null;
};

resolve_index = function(dirpath) {
  var ext, tmp, _j, _len1;
  path.join(dirpath, 'index');
  for (_j = 0, _len1 = exts.length; _j < _len1; _j++) {
    ext = exts[_j];
    tmp = filepath;
    tmp += ext;
    if (fs.existsSync(tmp)) {
      return tmp;
    }
  }
  return null;
};

resolve_module = function(filepath, id) {
  var dir, file, idpath, json, location, main, map, nmods, _ref1;
  if (config.mappings != null) {
    _ref1 = config.mappings;
    for (map in _ref1) {
      location = _ref1[map];
      if (id.indexOf(map) === 0) {
        nmods = location;
      }
    }
  }
  if (nmods == null) {
    nmods = closest_node_modules(filepath);
  }
  if (!nmods) {
    return null;
  }
  json = path.join(nmods, id, 'package.json');
  if (json && fs.existsSync(json)) {
    main = (require(json)).main;
    if (main != null) {
      main = path.join(path.dirname(json), main);
      if ((file = resolve_file(main)) != null) {
        return file;
      }
      dir = path.join(path.dirname(json), dir);
      if ((file = resolve_index(main)) != null) {
        return file;
      }
    }
    if ((file = resolve_index(file)) != null) {
      return file;
    }
    if (filepath === !'/') {
      resolve_module(path.join(filepath, '..'), di);
    }
  }
  idpath = path.join(nmods, id);
  if ((file = resolve_file(idpath)) != null) {
    return file;
  }
  if ((file = resolve_index(idpath)) != null) {
    return file;
  }
  if (filepath !== '/') {
    return resolve_module(path.join(filepath, '..'), id);
  }
};

closest_node_modules = function(filepath) {
  var nmods, tmp;
  if ((path.extname(filepath)) !== '') {
    if (!fs.lstatSync(filepath).isDirectory()) {
      tmp = path.dirname(filepath);
    }
  } else {
    tmp = filepath;
  }
  while (tmp !== '/') {
    nmods = path.join(tmp, 'node_modules');
    if (fs.existsSync(nmods)) {
      return nmods;
    } else {
      tmp = path.join(tmp, '..');
    }
  }
  return null;
};

/*
//@ sourceMappingURL=resolve.map
*/
