// Generated by CoffeeScript 1.6.3
(function() {
  var Cli, File, Files, compiler, config, fsu, path, plugins, _,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  path = require('path');

  fsu = require('fs-util');

  _ = require('lodash');

  config = require('../utils/config');

  compiler = require('./compiler');

  plugins = require('../utils/plugins');

  File = require('./file');

  Cli = require('../cli');

  module.exports = new (Files = (function() {
    var argv, cli, exts, plugin, _i, _len;

    argv = (cli = new Cli).argv;

    for (_i = 0, _len = plugins.length; _i < _len; _i++) {
      plugin = plugins[_i];
      exts = plugin.ext;
    }

    Files.prototype.files = null;

    Files.prototype.watchers = null;

    function Files() {
      this.onfschange = __bind(this.onfschange, this);
      var dirpath, filepath, _j, _k, _len1, _len2, _ref, _ref1;
      this.files = [];
      _ref = config.input;
      for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
        dirpath = _ref[_j];
        _ref1 = fsu.find(dirpath, exts);
        for (_k = 0, _len2 = _ref1.length; _k < _len2; _k++) {
          filepath = _ref1[_k];
          this.files.push(new File(filepath));
        }
      }
      if (argv.watch) {
        this.watch();
      }
    }

    Files.prototype.watch = function() {
      var dirpath, location, name, watcher, watchers, _j, _len1, _ref, _ref1, _results,
        _this = this;
      watchers = [];
      _ref = config.input;
      for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
        dirpath = _ref[_j];
        watchers.push((watcher = fsu.watch(dirpath, exts)));
        watcher.on('create', function(file) {
          return _this.onfschange(false, dirpath, 'create', file);
        });
        watcher.on('change', function(file) {
          return _this.onfschange(false, dirpath, 'change', file);
        });
        watcher.on('delete', function(file) {
          return _this.onfschange(false, dirpath, 'delete', file);
        });
      }
      _ref1 = config.vendors.js;
      _results = [];
      for (name in _ref1) {
        location = _ref1[name];
        watchers.push((watcher = fsu.watch(location)));
        watcher.on('create', function(file) {
          return _this.onfschange(true, dirpath, 'create', file);
        });
        watcher.on('change', function(file) {
          return _this.onfschange(true, dirpath, 'change', file);
        });
        _results.push(watcher.on('delete', function(file) {
          return _this.onfschange(true, dirpath, 'delete', file);
        }));
      }
      return _results;
    };

    Files.prototype.close_watchers = function() {
      var watcher, _j, _len1, _ref, _results;
      _ref = this.watchers;
      _results = [];
      for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
        watcher = _ref[_j];
        _results.push(watcher.close());
      }
      return _results;
    };

    Files.prototype.onfschange = function(vendor, dirpath, action, file) {
      var index, location, msg, type;
      location = file.location, type = file.type;
      if (type === "dir" && action === "create") {
        return;
      }
      switch (action) {
        case "create":
          this.files.push(new File(location));
          msg = ("+ " + type + " created").bold;
          console.log(("" + msg + " " + location).cyan);
          return compiler.build();
        case "delete":
          file = _.find(this.files, {
            filepath: location
          });
          index = _.indexOf(this.files, {
            filepath: location
          });
          if (file != null) {
            this.files.splice(index, 1);
            msg = ("- " + type + " deleted").bold;
            compiler.build();
            return console.log(("" + msg + " " + location).red);
          }
          break;
        case "change":
          file = _.find(this.files, {
            filepath: location
          });
          if (file === null && vendor === false) {
            msg = "Change file is apparently null, it shouldn't happened.\n";
            msg += "Please report this at the repo issues section.";
            console.warn(msg);
          } else {
            msg = ("• " + type + " changed").bold;
            console.log(("" + msg + " " + location).cyan);
          }
          file.refresh();
          return compiler.build();
      }
    };

    return Files;

  })());

}).call(this);

/*
//@ sourceMappingURL=files.map
*/
