// Generated by CoffeeScript 1.6.3
(function() {
  var File, MicroEvent, dirs, fs, path, plugins, prefix, scan, sufix,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  fs = require('fs');

  path = require('path');

  dirs = require('../utils/dirs');

  plugins = require('../utils/plugins');

  scan = require('../scanner/scan');

  MicroEvent = require('../event/microevent');

  prefix = "require.register('~path', function(exports, require, module){";

  sufix = "});";

  module.exports = File = (function(_super) {
    __extends(File, _super);

    File.prototype.raw = null;

    File.prototype.filepath = null;

    File.prototype.relativepath = null;

    File.prototype.id = null;

    File.prototype.type = null;

    File.prototype.deps = null;

    File.prototype.uncompiled = null;

    File.prototype.compiled = null;

    File.prototype.map = null;

    File.prototype.compiled = null;

    File.prototype.src_map = null;

    File.prototype.compiler = null;

    function File(filepath) {
      this.filepath = filepath;
      this.relativepath = dirs.relative(this.filepath);
      this.compiler = this.get_compiler();
      this.type = this.compiler.type;
    }

    File.prototype.init = function() {
      return this.refresh();
    };

    File.prototype.refresh = function() {
      var _this = this;
      this.raw = fs.readFileSync(this.filepath, "utf-8");
      return this.compile(function() {
        return _this.deps = _this.scan_deps();
      });
    };

    File.prototype.compile = function(done) {
      var _this = this;
      return this.compiler.compile(this.filepath, this.raw, function(compiled, map, uncompiled) {
        var outpath;
        _this.compiled = compiled;
        _this.map = map;
        _this.uncompiled = uncompiled;
        if (_this.type === 'css') {
          _this.wrapped = _this.compiled;
        }
        if (_this.type === 'js') {
          outpath = _this.relativepath.replace(_this.compiler.ext, '.js');
          _this.wrapped = prefix.replace('~path', outpath);
          _this.wrapped += "\n";
          _this.wrapped += _this.compiled;
          _this.wrapped += "\n";
          _this.wrapped += sufix;
        }
        return typeof done === "function" ? done(_this) : void 0;
      });
    };

    File.prototype.scan_deps = function() {
      var deps;
      this.emit('deps', deps = scan(this.filepath, this.compiler.exts, this.compiled));
      return deps;
    };

    File.prototype.get_compiler = function() {
      var plugin, _i, _len;
      for (_i = 0, _len = plugins.length; _i < _len; _i++) {
        plugin = plugins[_i];
        if (plugin.ext.test(this.filepath)) {
          return plugin;
        }
      }
    };

    return File;

  })(MicroEvent);

}).call(this);

/*
//@ sourceMappingURL=file.map
*/
