// Generated by CoffeeScript 1.6.3
var Cli, config, connect, debug, dirs, error, fs, info, io, log, path, refresher, sourcemaps, warn, _ref;

path = require('path');

fs = require('fs');

connect = require('connect');

io = require('socket.io');

dirs = require('../utils/dirs');

config = require('../utils/config');

sourcemaps = require('../utils/sourcemaps');

log = require('../utils/logger')('core/server');

_ref = log, error = _ref.error, warn = _ref.warn, info = _ref.info, debug = _ref.debug, log = _ref.log;

Cli = require('../cli');

refresher = null;

module.exports = function() {
  var address, argv, cli, index, port, root, _ref1;
  argv = (cli = new Cli).argv;
  _ref1 = config.server, root = _ref1.root, port = _ref1.port;
  index = path.join(root, 'index.html');
  connect().use(connect["static"](root)).use(function(req, res) {
    if (~(req.url.indexOf('.'))) {
      res.statusCode = 404;
      return res.end('File not found: ' + req.url);
    } else {
      return res.end(fs.readFileSync(index, 'utf-8'));
    }
  }).listen(port);
  address = 'http://localhost:' + port;
  log("♫  " + address);
  if (!argv.r) {
    return refresher = io.listen(53211, {
      'log level': 0
    });
  }
};

module.exports.reload = function(type) {
  var css_output;
  if (refresher == null) {
    return;
  }
  css_output = path.basename(config.output.css);
  return refresher.sockets.emit('refresh', {
    type: type,
    css_output: css_output
  });
};

/*
//@ sourceMappingURL=server.map
*/
