// Generated by CoffeeScript 1.6.3
(function() {
  var Cli, config, connect, fs, io, path, refresher;

  path = require('path');

  fs = require('fs');

  connect = require('connect');

  io = require('socket.io');

  config = require('../utils/config');

  Cli = require('../cli');

  refresher = null;

  module.exports = function() {
    var address, argv, cli, index, port, root, _ref;
    argv = (cli = new Cli).argv;
    _ref = config.server, root = _ref.root, port = _ref.port;
    index = path.join(root, 'index.html');
    connect().use(connect["static"](root)).use(function(req, res) {
      if (~(req.url.indexOf('.'))) {
        res.statusCode = 404;
        return res.end('File not found: ' + req.url);
      } else {
        return res.end(fs.readFileSync(index, 'utf-8'));
      }
    }).listen(port);
    address = 'http://localhost:' + port;
    console.log("♫  " + address);
    if (!argv.r) {
      return refresher = io.listen(53211, {
        'log level': 0
      });
    }
  };

  module.exports.reload = function(type) {
    var css_output;
    if (refresher == null) {
      return;
    }
    css_output = path.basename(config.output.css);
    return refresher.sockets.emit('refresh', {
      type: type,
      css_output: css_output
    });
  };

}).call(this);

/*
//@ sourceMappingURL=server.map
*/
