// Generated by CoffeeScript 1.6.3
(function() {
  var config, dirpath, dirs, index, path, yml, _i, _len, _ref, _ref1, _ref2;

  yml = require('js-yaml');

  path = require('path');

  dirs = require('./dirs');

  config = require(path.join(dirs.pwd, "polvo.yml"));

  _ref = config.input;
  for (index = _i = 0, _len = _ref.length; _i < _len; index = ++_i) {
    dirpath = _ref[index];
    config.input[index] = path.join(dirs.pwd, dirpath);
  }

  if (config.output.js) {
    config.output.js = path.join(dirs.pwd, config.output.js);
  }

  if (config.output.css) {
    config.output.css = path.join(dirs.pwd, config.output.css);
  }

  if (config.minify != null) {
    config.minify.js = (_ref1 = config.minify.js) != null ? _ref1 : true;
    config.minify.css = (_ref2 = config.minify.css) != null ? _ref2 : true;
  } else {
    config.minify = {
      js: true,
      css: true
    };
  }

  module.exports = config;

}).call(this);

/*
//@ sourceMappingURL=config.map
*/
