// Generated by CoffeeScript 1.6.3
(function() {
  var Cli, argv, cli, debug, error, fs, info, log, path, resolve_base, warn, _ref;

  path = require('path');

  fs = require('fs');

  Cli = require('../cli');

  log = require('./log')('polvo');

  argv = (cli = new Cli).argv;

  _ref = log, error = _ref.error, warn = _ref.warn, info = _ref.info, debug = _ref.debug, log = _ref.log;

  resolve_base = function() {
    var base;
    if (!fs.existsSync(base = path.resolve(argv.base || '.'))) {
      error('Dir informed with [--base] option doesn\'t exist ~>', base);
      return null;
    }
    return base;
  };

  module.exports = {
    root: path.join(__dirname, '..', '..'),
    pwd: resolve_base(),
    relative: function(filepath) {
      if (filepath.indexOf(this.pwd) === 0) {
        return filepath.replace("" + this.pwd + "/", '');
      } else {
        return path.relative(this.pwd, filepath);
      }
    }
  };

}).call(this);

/*
//@ sourceMappingURL=dirs.map
*/
