// Generated by CoffeeScript 1.6.3
var cli, debug, error, fs, info, log, path, warn, _ref;

path = require('path');

fs = require('fs');

cli = require('../cli');

log = require('./log')('polvo');

_ref = log, error = _ref.error, warn = _ref.warn, info = _ref.info, debug = _ref.debug, log = _ref.log;

exports.root = function() {
  return path.join(__dirname, '..', '..');
};

exports.pwd = function() {
  var argv, pwd;
  argv = cli.argv();
  if (argv.base != null) {
    if (!fs.existsSync((pwd = path.resolve(argv.base)))) {
      error('Dir informed with [--base] option doesn\'t exist ~>', argv.base);
      return null;
    } else {
      return pwd;
    }
  }
  return path.resolve('.');
};

exports.relative = function(filepath) {
  return path.relative(exports.pwd(), filepath);
};

/*
//@ sourceMappingURL=dirs.map
*/
