// Generated by CoffeeScript 1.6.3
(function() {
  var Cli, argv, cli, path;

  path = require('path');

  Cli = require('../cli');

  argv = (cli = new Cli).argv;

  module.exports = {
    root: path.join(__dirname, '..', '..'),
    pwd: path.resolve(argv.base || '.'),
    relative: function(filepath) {
      if (~filepath.indexOf(this.pwd)) {
        return filepath.replace("" + this.pwd + "/", '');
      } else {
        return path.relative(this.pwd, filepath);
      }
    }
  };

}).call(this);

/*
//@ sourceMappingURL=dirs.map
*/
