// Generated by CoffeeScript 1.6.3
(function() {
  var Log, colors, util,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __slice = [].slice;

  util = require('util');

  colors = require('colors');

  module.exports = Log = (function() {
    Log.prototype.alias = null;

    function Log(alias) {
      if (alias == null) {
        alias = null;
      }
      this.debug = __bind(this.debug, this);
      this.info = __bind(this.info, this);
      this.warn = __bind(this.warn, this);
      this.error = __bind(this.error, this);
      this.alias = alias.grey;
    }

    Log.prototype.error = function() {
      var args, msg, output;
      msg = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      output = ['error'.red, msg.grey].concat(args);
      return console.log.apply(null, output);
    };

    Log.prototype.warn = function() {
      var args, msg, output;
      msg = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      output = [' warn'.yellow, msg.grey].concat(args);
      return console.log.apply(null, output);
    };

    Log.prototype.info = function() {
      var args, msg, output;
      msg = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      output = [' info'.cyan, msg.grey].concat(args);
      return console.log.apply(null, output);
    };

    Log.prototype.debug = function() {
      var args, msg, output;
      msg = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      output = [this.alias, 'debug'.magenta, msg.grey].concat(args);
      return console.log.apply(null, output);
    };

    return Log;

  })();

}).call(this);

/*
//@ sourceMappingURL=log.map
*/
