// Generated by CoffeeScript 1.6.3
var argv, cli, colors, dirs, log_to_stderr, log_to_stdout, util,
  __slice = [].slice;

util = require('util');

colors = require('colors');

dirs = null;

cli = require('../cli');

argv = cli.argv();

log_to_stdout = function(args) {
  args = [].concat(args);
  if (typeof __stdout !== "undefined" && __stdout !== null) {
    return __stdout(args.join(' ').stripColors);
  } else {
    return console.log.apply(null, args);
  }
};

log_to_stderr = function(args) {
  args = [].concat(args);
  if (typeof __stderr !== "undefined" && __stderr !== null) {
    return __stderr(args.join(' ').stripColors);
  } else {
    return console.error.apply(null, args);
  }
};

module.exports = function(alias) {
  if (alias == null) {
    alias = '';
  }
  dirs = require('./dirs');
  return {
    error: function() {
      var args, msg;
      msg = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      return log_to_stderr(['error'.bold.red, msg.grey].concat(args));
    },
    warn: function() {
      var args, msg;
      msg = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      return log_to_stderr(['warn'.bold.yellow, msg.grey].concat(args));
    },
    info: function() {
      var args, msg;
      msg = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      return log_to_stdout(['info'.bold.cyan, msg.grey].concat(args));
    },
    debug: function() {
      var args, msg;
      msg = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      if (alias === '') {
        return log_to_stdout(['debug'.magenta, msg.grey].concat(args));
      } else {
        return log_to_stdout([alias.inverse, 'debug'.magenta, msg.grey].concat(args));
      }
    },
    file: {
      created: function(filepath) {
        return log_to_stdout(("+ " + (dirs.relative(filepath))).green);
      },
      changed: function(filepath) {
        return log_to_stdout(("• " + (dirs.relative(filepath))).yellow);
      },
      deleted: function(filepath) {
        return log_to_stdout(("- " + (dirs.relative(filepath))).red);
      },
      compiled: function(filepath) {
        return log_to_stdout(("✓ " + (dirs.relative(filepath))).cyan);
      }
    }
  };
};

/*
//@ sourceMappingURL=log.map
*/
