// Generated by CoffeeScript 1.6.3
var alias, argv, cli, colors, dirs, log_to_stderr, log_to_stdout, util,
  __slice = [].slice;

util = require('util');

colors = require('colors');

dirs = null;

cli = require('../cli');

alias = '';

argv = cli.argv();

log_to_stdout = function(args) {
  args = [].concat(args);
  if (process.send && !argv.stdio) {
    return process.send({
      channel: 'stdout',
      msg: args.join(' ')
    });
  } else if (typeof __stdout !== "undefined" && __stdout !== null) {
    return __stdout(args.join(' ').stripColors);
  } else {
    return console.log.apply(null, args);
  }
};

log_to_stderr = function(args) {
  args = [].concat(args);
  if (process.send && !argv.stidio) {
    return process.send({
      channel: 'stderr',
      msg: args.join(' ')
    });
  } else if (typeof __stderr !== "undefined" && __stderr !== null) {
    return __stderr(args.join(' ').stripColors);
  } else {
    return console.error.apply(null, args);
  }
};

module.exports = function(_alias) {
  dirs = require('./dirs');
  alias = (_alias || alias).grey;
  return module.exports;
};

module.exports.error = function() {
  var args, msg;
  msg = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
  return log_to_stderr(['error'.bold.red, msg.grey].concat(args));
};

module.exports.warn = function() {
  var args, msg;
  msg = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
  return log_to_stderr([' warn'.bold.yellow, msg.grey].concat(args));
};

module.exports.info = function() {
  var args, msg;
  msg = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
  return log_to_stdout = [' info'.bold.cyan, msg.grey].concat(args);
};

module.exports.debug = function() {
  var args, msg;
  msg = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
  return log_to_stdout = [alias.inverse, 'debug'.magenta, msg.grey].concat(args);
};

module.exports.log = function() {
  var args;
  args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  return log_to_stdout(args);
};

module.exports.file = {
  created: function(filepath) {
    return log_to_stdout(("+ " + (dirs.relative(filepath))).green);
  },
  changed: function(filepath) {
    return log_to_stdout(("• " + (dirs.relative(filepath))).yellow);
  },
  deleted: function(filepath) {
    return log_to_stdout(("- " + (dirs.relative(filepath))).red);
  },
  compiled: function(filepath) {
    return log_to_stdout(("✓ " + (dirs.relative(filepath))).cyan);
  }
};

/*
//@ sourceMappingURL=log.map
*/
