// Generated by CoffeeScript 1.6.3
var cleancss, uglify;

uglify = require('uglify-js');

cleancss = require('clean-css');

exports.js = function(uncompressed) {
  var ast, compiled, stream;
  ast = uglify.parse(uncompressed);
  stream = uglify.OutputStream();
  ast.print(stream);
  return compiled = stream.toString();
};

exports.css = function(uncompressed) {
  return cleancss.process(uncompressed);
};

exports.html = function(uncompressed) {
  return uncompressed.replace(/\n/g, '');
};

/*
//@ sourceMappingURL=minify.map
*/
