// Generated by CoffeeScript 1.6.3
(function() {
  var uglify;

  uglify = require('uglify-js');

  exports.js = function(uncompressed) {
    var ast, compiled, stream;
    ast = uglify.parse(uncompressed);
    stream = uglify.OutputStream();
    ast.print(stream);
    return compiled = stream.toString();
  };

  exports.css = function(uncompressed) {
    return uncompressed;
  };

}).call(this);

/*
//@ sourceMappingURL=minify.map
*/
