// Generated by CoffeeScript 1.6.3
var argv, debug, error, fs, humanize, info, log_compiled, logger, warn, zlib;

fs = require('fs');

zlib = require('zlib');

humanize = require('humanize');

argv = require('../cli').argv;

logger = require('../utils/logger')('core/compiler');

error = logger.error, warn = logger.warn, info = logger.info, debug = logger.debug;

log_compiled = logger.file.compiled;

module.exports = function(filepath, done) {
  var fsize;
  fsize = humanize.filesize(fs.statSync(filepath).size);
  if (!argv.release) {
    log_compiled("" + filepath + " (" + fsize + ")");
    return typeof done === "function" ? done() : void 0;
  }
  return zlib.gzip(fs.readFileSync(filepath, 'utf-8'), function(err, gzip) {
    var gsize;
    fs.writeFileSync(filepath + '.tmp.gzip', gzip);
    gsize = humanize.filesize(fs.statSync(filepath + '.tmp.gzip').size);
    log_compiled("" + filepath + " (" + fsize + ") (" + gsize + " gzipped)");
    fs.unlinkSync(filepath + '.tmp.gzip');
    return typeof done === "function" ? done() : void 0;
  });
};

/*
//@ sourceMappingURL=notifier.map
*/
