// Generated by CoffeeScript 1.6.3
var dirs, fs, path, plugins, scan, util, _;

_ = require('lodash');

fs = require('fs');

path = require('path');

util = require('util');

dirs = require('../utils/dirs');

plugins = [];

scan = function(manifest_path) {
  var err, manifest, plugin, _results;
  if (!fs.existsSync(manifest_path)) {
    return;
  }
  manifest = require(manifest_path);
  _results = [];
  for (plugin in manifest.dependencies) {
    try {
      plugin = require(path.join(dirs.root, 'node_modules', plugin));
      if (plugin.polvo) {
        _results.push(plugins.push(plugin));
      } else {
        _results.push(void 0);
      }
    } catch (_error) {
      err = _error;
      continue;
    }
  }
  return _results;
};

scan(path.join(dirs.root, 'package.json'));

scan(path.join(dirs.pwd, 'package.json'));

module.exports = plugins;

/*
//@ sourceMappingURL=plugins.map
*/
