// Generated by CoffeeScript 1.6.3
var app_json, dirs, error, fs, get_plugin_manifest, info, path, plugins, registered, scan, util, _, _ref;

_ = require('lodash');

fs = require('fs');

path = require('path');

util = require('util');

dirs = require('../utils/dirs');

_ref = require('../utils/logger')('utils/plugins'), error = _ref.error, info = _ref.info;

plugins = [];

registered = {};

get_plugin_manifest = function(folder, plugin) {
  var current, manifest;
  manifest = path.join(folder, 'node_modules', plugin, 'package.json');
  if (fs.existsSync(manifest)) {
    return manifest;
  }
  current = path.dirname(require.resolve(plugin));
  while (current !== '/') {
    manifest = path.join(current, 'package.json');
    if (fs.existsSync(manifest)) {
      return manifest;
    } else {
      current = path.join(current, '..');
    }
  }
};

scan = function(folder) {
  var absolute, manifest, manifest_path, pfolder, plugin, pmanifest, _results;
  manifest_path = path.join(folder, 'package.json');
  manifest = require(manifest_path);
  _results = [];
  for (plugin in manifest.dependencies) {
    absolute = get_plugin_manifest(folder, plugin);
    pfolder = path.join(folder, 'node_modules', plugin);
    pmanifest = require(path.join(pfolder, 'package.json'));
    if (pmanifest.polvo && !registered[pmanifest.name]) {
      registered[pmanifest.name] = true;
      _results.push(plugins.push(require(plugin)));
    } else {
      _results.push(void 0);
    }
  }
  return _results;
};

scan(path.join(dirs.root()));

app_json = path.join(dirs.pwd(), 'package.json');

if (fs.existsSync(app_json)) {
  scan(dirs.pwd());
} else {
  info('app doesn\'t have a `package.json` file, loading built-in plugins only');
}

module.exports = plugins;

/*
//@ sourceMappingURL=plugins.map
*/
