// Generated by CoffeeScript 1.6.3
(function() {
  var config, dirs, fs, map, path, section, sourcemaps;

  path = require('path');

  fs = require('fs');

  dirs = require('./dirs');

  config = require('./config');

  map = "{\n  \"version\": 3,\n  \"file\": \"~FILE\",\n  \"sections\": [\n    ~SECTIONS\n  ]\n}";

  section = "{\n  \"offset\": {\n    \"line\":~LINE,\n    \"column\":0\n  },\n  \"map\": {\n    \"version\": 3,\n    \"file\": \"app.js\",\n    \"sourceRoot\": \"http://localhost:" + config.server.port + "/__source_maps\",\n    \"sources\": [\"~SOURCE\"],\n    \"names\": [],\n    \"mappings\": \"~MAPS\"\n  }\n}";

  sourcemaps = null;

  exports.assemble = function(files) {
    var buffer, file, sbuffer, sections, _i, _len;
    buffer = map.replace('~FILE', path.basename(config.output.js));
    sections = [];
    for (_i = 0, _len = files.length; _i < _len; _i++) {
      file = files[_i];
      if (!(file.source_map != null)) {
        continue;
      }
      sbuffer = section.replace('~SOURCE', dirs.relative(file.filepath));
      sbuffer = sbuffer.replace('~LINE', file.source_map_offset);
      sbuffer = sbuffer.replace('~MAPS', JSON.parse(file.source_map).mappings);
      sections.push(sbuffer);
    }
    return sourcemaps = buffer.replace('~SECTIONS', sections.join(',\n'));
  };

  exports.get_assembled = function() {
    return sourcemaps;
  };

}).call(this);

/*
//@ sourceMappingURL=sourcemaps.map
*/
