// Generated by CoffeeScript 1.6.3
var config, dirs, fs, path;

path = require('path');

fs = require('fs');

dirs = require('./dirs');

config = require('./config');

exports.assemble = function(files) {
  var file, map, _i, _len;
  map = {
    version: 3,
    file: path.basename(config.output.js),
    sections: []
  };
  for (_i = 0, _len = files.length; _i < _len; _i++) {
    file = files[_i];
    if (file.source_map != null) {
      map.sections.push({
        offset: {
          line: file.source_map_offset,
          column: 0
        },
        map: {
          version: 3,
          file: 'app.js',
          sources: [dirs.relative(file.filepath)],
          sourcesContent: [file.raw],
          names: [],
          mappings: JSON.parse(file.source_map).mappings
        }
      });
    }
  }
  return JSON.stringify(map);
};

exports.encode_base64 = function(map) {
  return new Buffer(map).toString('base64');
};

/*
//@ sourceMappingURL=sourcemaps.map
*/
