// Generated by CoffeeScript 1.6.3
(function() {
  var XRegExp, debug, error, javascript, log, path, warn, _ref;

  path = require('path');

  XRegExp = require('xregexp').XRegExp;

  _ref = require('./../utils/log-util'), log = _ref.log, debug = _ref.debug, warn = _ref.warn, error = _ref.error;

  module.exports = javascript = (function() {
    var AMD_WRAPPER;

    function javascript() {}

    javascript.NAME = 'javascript';

    javascript.TYPE = 'javascript';

    javascript.EXT = /\.(js)?$/m;

    AMD_WRAPPER = "/*\n  Assembled by Polvo\n*/\n~global_code\ndefine(['require', 'exports', 'module'], function(require, exports, module)\n{\n~code\n});";

    javascript.compile = function(file, after_compile) {
      var clean, contents, global_code, global_reg, global_res, raw;
      raw = file.raw;
      global_reg = XRegExp('\/\/>>\n(.*)\n\/\/<<', 's');
      global_res = XRegExp.exec(file.raw, global_reg);
      global_code = global_res != null ? global_res[1] : '';
      clean = raw.replace(global_code, '');
      contents = AMD_WRAPPER.replace('~code', this.reindent(clean));
      contents = contents.replace('~global_code', global_code);
      return after_compile(contents);
    };

    javascript.translate_ext = function(filepath) {
      return filepath;
    };

    javascript.strip_ext = function(filepath) {
      return filepath.replace(this.EXT, '');
    };

    javascript.reindent = function(code) {
      var indentation, match_indentation;
      match_indentation = /^(\s+).*$/mg;
      indentation = '';
      while ((indentation.match(/^[ \t]{2,}/m)) == null) {
        indentation = match_indentation.exec(code);
        if (indentation != null) {
          indentation = indentation[1];
        } else {
          indentation = "  ";
        }
      }
      indentation = indentation.replace(/[\r\n]/g, '');
      return code.replace(/^/mg, "" + indentation);
    };

    return javascript;

  })();

}).call(this);

/*
//@ sourceMappingURL=javascript.map
*/
