// Generated by CoffeeScript 1.6.2
(function() {
  var Stylus, debug, error, log, nib, stylus, warn, _ref;

  stylus = require('stylus');

  nib = require('nib');

  _ref = require('./../utils/log-util'), log = _ref.log, debug = _ref.debug, warn = _ref.warn, error = _ref.error;

  module.exports = Stylus = (function() {
    var AMD_WRAPPER;

    function Stylus() {}

    Stylus.NAME = 'stylus';

    Stylus.TYPE = 'style';

    Stylus.EXT = /(\/)([^\/_]+)(\.styl)$/m;

    AMD_WRAPPER = "// Compiled by Polvo, using Stylus\ndefine(['require', 'exports', 'module'], function(require, exports, module){\n  var style = module.exports = document.createElement('style');\n  var head = document.getElementsByTagName('head')[0];\n\n  style.id = '~id';\n  style.appendChild(document.createTextNode('~css'));\n  head.insertBefore(style, head.lastChild);\n\n  return style;\n});";

    Stylus.compile = function(file, after_compile) {
      var _this = this;

      return stylus(file.raw).set('filename', file.absolute_path).use(nib())["import"]('nib').render(function(err, css) {
        var wrapped;

        if (err != null) {
          return error(err);
        }
        wrapped = AMD_WRAPPER.replace('~css', css.replace(/\n|\r/g, ''));
        wrapped = wrapped.replace(/~id/g, file.id);
        return after_compile(wrapped);
      });
    };

    Stylus.translate_ext = function(filepath) {
      return filepath.replace(this.EXT, '$1$2.js');
    };

    Stylus.strip_ext = function(filepath) {
      return filepath.replace(this.EXT, '$1$2');
    };

    return Stylus;

  })();

}).call(this);

/*
//@ sourceMappingURL=stylus.map
*/
